### ISSUE TITLE
Error - Linker command failed

### ISSUE THREAD

**Issue by TheNotoriousCoder** [jaksatomovic/Snapgram#1]
@jaksatomovic 
Hello, I wanted to test out your app. However, there's an error _"Linker command failed with exit code 1 (use -v to see invocation)"_ You've imported/added all your ".m" files, I've disabled bitcode, to no avail. Do you know what the problem is?

Kudos on the app. Looks amazing.

**Comment by jaksatomovic** [comment]
It is probably error after uploading it to github because i have had difficulty uploading it cause files were to large so i did it in few steps.However i will check it and let you know if i find out anything :)

**Comment by jaksatomovic** [comment]
Here is the solution:

There seems to be an issue with Xcode 7 beta where the search path for manually added frameworks is missing.

To fix the issue add the search path by doing the following:

1. Select Project
2. Click on Targets
3. Click Build Settings
3. Search for: Framework Search Path
4. Add $(PROJECT_DIR) and choose Recursive option.
The project should build now.


If it doesnt work try installing PARSE SDK with cocoapods...just init new Pod file and add parse sdk then install pods

**Comment by jaksatomovic** [comment]
http://stackoverflow.com/questions/32687105/framework-not-found-xcode

**Comment by TheNotoriousCoder** [comment]
@jaksatomovic 

Thanks for your reply. Sadly, I could not amend the issue. 

May I ask you a few questions, regarding this application?

- Does this application have an activity feed where notifications will appear if a user likes/comments/followers another individual?

- Does the application allow searching via hashtags? 

- Where displaying all users, are all users retrieved first and then filtered by the string entered in the search-bar or is the string passed through to the back-end to find a match?


Thank you.

**Comment by TheNotoriousCoder** [comment]
Also, may I asked what resources, if any, you used to create this app? I'm looking to create something very similar, but wished to take a look at yours to understand what's going on behind the scenes and use Firebase as my backend.

**Comment by jaksatomovic** [comment]
Hello..first answer to your questions..Yes it does it has what you asked for..i will try te upload code again cause my version on mac works but downloaded one doesn't..i have only used parse sdk for my backend which is hosted on heroku..for me parse is easier cause i havent worked with firebase...u have likes, followings etc..

**Comment by TheNotoriousCoder** [comment]
@jaksatomovic 

Dude! I'm such an idiot! I just had to install the pod file! I am sooooo sorry!!!  

I'm testing out your app! It's amazing! Would you mind if I used it as a guideline so I can create a similar app? Code may be the same, concept will be the same but will type it out myself. It won't be a simple copy and paste.

When testing, I can't add comments? I hit the send button but nothing works?

**Comment by jaksatomovic** [comment]
I am happy u have succed! :) Don't worry use it however u want...anyway here is the link from dropbox, maybe comments work on this link cause this is version from my mac and everything works here: https://www.dropbox.com/sh/56q3op2f2d6kjr4/AACf9AV9hmb0j1Xzr5HlReLwa?dl=0

**Comment by TheNotoriousCoder** [comment]
@jaksatomovic 

If I was a woman, I would sleep with you! Lol! Thank you soooooo much man! I love you! #BroMance

**Comment by TheNotoriousCoder** [comment]
@jaksatomovic 

Just used the dropbox version, this one displayed the activity icon when a like/person follows.

However, still have issues with the commenting. Do you use the simulator keyboard to comment?

**Comment by jaksatomovic** [comment]
Yes  use simulator keyboard only...try experimenting with those three options of keyboard in simulator Device>Keyboard or similar :p

**Comment by TheNotoriousCoder** [comment]
@jaksatomovic I will do, your project is 90% of my final app. I have a load more features to implement but this is a great starting point!

I have used the keyboard, however, it appears the button is either disabled or behind another view. There is no indication that the button has been selected, usually the colour of the button changes. It just appears solid.

**Comment by jaksatomovic** [comment]
hmmm..i don't know  i did this a long ago so i am not sure hmmm probably but i can  tell you that it was all working before so expermient with code you will solve it maybe ...p.s. i will mark this issue as closed if its ok with you

**Comment by TheNotoriousCoder** [comment]
Yes I will experiment! And sure that's fine! Thank you for your generosity in allowing myself to use this project as a template. And thank you for your time!
